site_name: paranoidNAS
repo_name: paranoidnas/paranoidnas
repo_url: https://github.com/paranoidnas/paranoidnas
theme:
  name: material
  palette:
    scheme: default
    primary: indigo
    accent: indigo
  font:
    text: Fira Sans
    code: Fira Code
markdown_extensions:
  - codehilite
  - admonition
  - footnotes
  - pymdownx.snippets:
      check_paths: true
      base_path: .
nav:
  - Home: index.md
  - Getting started: getting-started.md
  - Design: design.md
  - Post-Installation: post-install.md
  - Monitoring: monitoring.md
  - Cloud Backup: cloud-backup.md
  - Recovery: recovery.md
  - System Services: system-services.md
  - Hosting Services: hosting-services.md
  - Contributing: contributing.md
