site_name: BlockCaptain
repo_name: blockcaptain/blockcaptain
repo_url: https://github.com/blockcaptain/blockcaptain
theme:
  name: material
  palette:
    scheme: default
    primary: indigo
    accent: indigo
  font:
    text: Fira Sans
    code: Fira Code
  features:
    - tabs
  custom_dir: blkcapt
markdown_extensions:
  - codehilite
  - admonition
  - footnotes
  - pymdownx.snippets:
      check_paths: true
      base_path: .
nav:
  - Home: index.md
  - BlockCaptain:
      - Design: blkcapt/design.md
      - Getting started: blkcapt/getting-started.md
      - Monitoring: blkcapt/monitoring.md
      - Cloud Backup: blkcapt/cloud-backup.md
      - Recovery: blkcapt/recovery.md
  - NAS:
      - Design: nas/design.md
      - Getting started: nas/getting-started.md
      - Post-Installation: nas/post-install.md
      - System Services: nas/system-services.md
      - Hosting Services: nas/hosting-services.md
  - Development:
      - Contributing: development/contributing.md
