name: Publish Docs

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
        with:
          path: code
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('code/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r code/requirements.txt
      - name: Workaround Snippets Issue
        working-directory: code
        run: |
          sed -i "s|base_path: .|base_path: $PWD|" mkdocs.yml
      - name: Setup Git
        run: |
          git config --global user.email "67969363+rebeaglebot@users.noreply.github.com"
          git config --global user.name "rebeaglebot"
      - name: Get GH Pages Repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.BOT_TOKEN }}
          repository: paranoidnas/paranoidnas.github.io
          path: pages
      - name: Publish
        working-directory: pages
        run: |
          mkdocs gh-deploy --config-file ../code/mkdocs.yml --remote-branch master
